export const LANGUAGES = {
  en: "English",
  fr: "French",
  de: "German",
  it: "Italian",
  ja: "Japanese",
  ko: "Korean",
  pl: "Polish",
  pt: "Portuguese",
  es: "Spanish",
  sv: "Swedish",
  tr: "Turkish",
  uk: "Ukrainian",
  zh: "Chinese",
  ar: "Arabic",
  bn: "Bengali",
  fi: "Finnish",
  id: "Indonesian",
  ka: "Georgian",
  my: "Burmese",
  ne: "Nepali",
  ro: "Romanian",
  si: "Sinhala",
  ur: "Urdu",
} as const;

export type LanguageType = keyof typeof LANGUAGES;
